
#maxCount can be "max" or "default" or positive integer (1~2147483646)
#The larger the number "priority", the higher the priority.
[[items]]
	tag = "forge:stackable"
	priority = 0
	maxCount = "default"

[[items]]
	name = "minecraft:potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:lingering_potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:splash_potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:mushroom_stew"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:enchanted_book"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:bread"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:blue_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:red_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:black_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:brown_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:cyan_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:gray_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:green_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:light_blue_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:light_gray_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:lime_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:magenta_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:orange_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:pink_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:purple_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:white_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:yellow_bed"
	priority = 1000
	maxCount = 64

