
#maxCount can be "max" or "default" or positive integer (1~2147483646)
#The larger the number "priority", the higher the priority.
[[items]]
	tag = "forge:stackable"
	priority = 0
	maxCount = "default"

[[items]]
	name = "minecraft:potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:lingering_potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:splash_potion"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:mushroom_stew"
	priority = 1000
	maxCount = "max"

[[items]]
	name = "minecraft:enchanted_book"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:bread"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:blue_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:red_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:black_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:brown_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:cyan_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:gray_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:green_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:light_blue_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:light_gray_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:lime_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:magenta_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:orange_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:pink_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:purple_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:white_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:yellow_bed"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:totem_of_undying"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:saddle"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:iron_horse_armor"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:diamond_horse_armor"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_13"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_cat"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_blocks"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_chirp"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_far"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_mall"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_mellohi"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_stal"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_strad"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_ward"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_11"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_wait"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_otherside"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_5"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_pigstep"
	priority = 1000
	maxCount = 64

[[items]]
	name = "minecraft:music_disc_relic"
	priority = 1000
	maxCount = 64

