
[svmm]
	#Whether or not the entire mod is disabled
	mod_disabled = false
	#Whether or not the mod is disabled by default for new players.
	#They may enable it with /svmm enable
	mod_disabled_default = false
	#Whether or not the entire mod is restricted by default for new users
	default_restricted = false
	#The maximum amount of blocks the mod is allowed to break at once
	#Range: > 1
	maximum_blocks_to_break = 100
	#The blocks that are allowed to be vein-mined
	block_white_list = ["#forge:ores"]
	#The blocks that will not be veinmined, even if they're part of the whitelist
	block_black_list = ["minecraft:ancient_debris"]
	#Whether or not to stop the vein mining when the tool is about to break
	stop_when_about_to_break_tool = true
	#Whether or not to teleport the mined items to the player
	teleport_items_to_player = true
	#Whether or not to allow moderators to modify the config at runtime
	runtime_config_edit_disabled = false
	#The default condition for when the mod triggers that new players will have
	#Allowed Values: SHIFT_HELD, SHIFT_NOT_HELD, ALWAYS
	trigger_when_default = "SHIFT_NOT_HELD"

	[svmm.giant-vein-mining]
		#Whether or not giant vein mining is disabled on the server
		giant_vein_mining_disabled = false
		#Whether or not giant vein mining is disabled by default for new players.
		#They may enable it with /svmm enable giantVein
		giant_vein_mining_default_disabled = false
		#Whether or not giant vein mining is restricted by default for new players
		giant_vein_mining_default_restricted = false
		#The blocks the player needs to mine before the giant vein miner is triggered
		giant_vein_starter_ore = ["minecraft:copper_ore", "minecraft:iron_ore", "minecraft:deepslate_copper_ore", "minecraft:deepslate_iron_ore", "minecraft:raw_copper_block", "minecraft:raw_iron_block"]
		#Blocks the giant vein miner is allowed to mine when triggered
		giant_vein_whitelist = ["minecraft:copper_ore", "minecraft:iron_ore", "minecraft:deepslate_copper_ore", "minecraft:deepslate_iron_ore", "minecraft:raw_copper_block", "minecraft:raw_iron_block", "minecraft:tuff"]
		#Blocks the giant vein miner won't mine when triggered
		giant_vein_blacklist = []

	[svmm.tunneling]
		#Whether or not tunneling is disabled on the server
		tunneling_disabled = false
		#Whether or not tunneling is restricted by default for new players.
		#Moderators may allow it for players with /svmm enable {player_name} tunneling
		tunneling_default_restricted = false
		#Whether or not to log to console whenever a player tunnels
		tunneling_logging = true
		#The maximum width & height for a tunnel
		#Range: > 1
		tunneling_max_dimensions = 5
		#How deep a tunnel is allowed to go at once
		#Range: > 1
		tunneling_max_depth = 50
		#How many blocks a tunnel may break at once. Has priority on dimensions and depth
		#Range: > 1
		tunneling_max_blocks = 100
		#Whether or not tunneling should stop when it encounters a different block from the starting block
		tunneling_same_type = false
		#The blocks the player is allowed to tunnel through
		tunneling_whitelist = ["minecraft:stone", "minecraft:deepslate", "minecraft:tuff", "minecraft:andesite", "minecraft:granite", "minecraft:diorite", "minecraft:calcite", "minecraft:dirt", "minecraft:sand", "minecraft:red_sand", "minecraft:gravel", "minecraft:sandstone", "minecraft:red_sandstone", "minecraft:grass", "minecraft:dripstone_block", "minecraft:podzol", "minecraft:mud", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:amethyst_block", "minecraft:obsidian", "minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice", "minecraft:snow_block", "minecraft:clay", "minecraft:netherrack", "minecraft:soul_sand", "minecraft:soul_soil", "minecraft:basalt", "minecraft:blackstone", "minecraft:glowstone", "minecraft:end_stone", "minecraft:terracotta", "minecraft:white_terracotta", "minecraft:orange_terracotta", "minecraft:magenta_terracotta", "minecraft:light_blue_terracotta", "minecraft:yellow_terracotta", "minecraft:lime_terracotta", "minecraft:pink_terracotta", "minecraft:gray_terracotta", "minecraft:light_gray_terracotta", "minecraft:cyan_terracotta", "minecraft:purple_terracotta", "minecraft:blue_terracotta", "minecraft:brown_terracotta", "minecraft:green_terracotta", "minecraft:red_terracotta", "minecraft:black_terracotta"]
		#The blocks the player is not allowed to tunnel through
		tunneling_blacklist = ["minecraft:obsidian"]

	[svmm.force-vein-mining]
		#Whether or not /svmm force is disabled on the server
		force_disabled = false
		#Whether or not /svmm force is restricted by default
		force_default_restricted = true
		#Whether or not to log to console whenever a player uses the force vein mine
		force_logging = true
		#Blocks that aren't allowed to be force vein mined
		force_blacklist = ["minecraft:bedrock", "minecraft:reinforced_deepslate", "minecraft:chest", "minecraft:trapped_chest", "minecraft:barrel"]

